#Homepage
base_url: https://my.eu.samsung.com/mysamsung/login?language=uk

#Valid credentials
valid_login_username: engeeforever@yahoo.co.uk
valid_login_password: PA33word_


#Inalid credentials
invalid_login_username: mghiheisgoishgoir@yahoo.co.uk
invalid_login_password: asbguigahowf5856
